import { groupByRound, truncate } from "./helpers.js";
import type { Renderer } from "./types.js";

export const renderMarkdown: Renderer = (input) => {
	const lines: string[] = [];
	lines.push(`# ${input.meeting.title}`);
	lines.push("");
	lines.push("```yaml");
	lines.push(`meetingId: ${input.meeting.id}`);
	lines.push(`status: ${input.meeting.status}`);
	lines.push(`createdAt: ${input.meeting.createdAt}`);
	if (input.meeting.endedAt) {
		lines.push(`endedAt: ${input.meeting.endedAt}`);
	}
	lines.push("```");

	lines.push("");
	lines.push("## Participants");
	lines.push("");
	lines.push("| id | role | adapter | status |");
	lines.push("|---|---|---|---|");
	for (const p of input.participants) {
		lines.push(`| \`${p.id}\` | ${p.role} | ${p.adapter ?? "—"} | ${p.status} |`);
	}
	const memberCount = input.participants.filter((p) => p.role === "member").length;
	lines.push("");
	lines.push(
		`_Symmetric peer deliberation — ${memberCount} member${
			memberCount === 1 ? "" : "s"
		} + 1 facilitator._`,
	);

	if (input.jobs.length > 0) {
		lines.push("");
		lines.push("## Jobs");
		lines.push("");
		lines.push("| jobId | status | reason | rounds | lastSeq |");
		lines.push("|---|---|---|---|---|");
		for (const job of input.jobs) {
			const reason = job.terminationReason ?? job.cancelReason ?? job.error?.code ?? "(none)";
			lines.push(
				`| \`${job.id}\` | ${job.status} | ${reason} | ${job.rounds} | ${job.lastSeq} |`,
			);
		}
	}

	lines.push("");
	lines.push("## Transcript");
	if (input.events !== null) {
		lines.push("");
		lines.push("```json");
		lines.push(JSON.stringify(input.events, null, 2));
		lines.push("```");
	} else {
		const groups = groupByRound(input.messages);
		for (const group of groups) {
			lines.push("");
			lines.push(`### ${group.round === 0 ? "Opening" : `Round ${group.round}`}`);
			lines.push("");
			for (const m of group.messages) {
				if (m.kind === "pass") {
					lines.push(`_${m.author} passed._`);
					lines.push("");
				} else if (m.kind === "system") {
					lines.push("---");
					lines.push("");
					lines.push(`> ⚠ ${truncate(m.text, 500)}`);
					lines.push("");
				} else {
					lines.push(`**${m.author}** — \`${m.createdAt}\``);
					lines.push("");
					for (const ln of m.text.split("\n")) {
						lines.push(`> ${ln}`);
					}
					lines.push("");
				}
			}
		}
	}

	lines.push("");
	lines.push(`<sub>Generated by veche ${input.version} · ${input.generatedAt}</sub>`);
	return `${lines.join("\n")}\n`;
};
