import { ansi, groupByRound, truncate } from "./helpers.js";
import type { Renderer } from "./types.js";

const HR = "─".repeat(64);

export const renderText: Renderer = (input) => {
	const c = ansi(input.useColor);
	const lines: string[] = [];

	// Header
	lines.push(c.bold(input.meeting.title));
	lines.push(c.dim(`meetingId: ${input.meeting.id}`));
	const statusTag =
		input.meeting.status === "active"
			? c.green(input.meeting.status)
			: c.grey(input.meeting.status);
	lines.push(`status:    ${statusTag}`);
	lines.push(c.dim(`created:   ${input.meeting.createdAt}`));
	if (input.meeting.endedAt) {
		lines.push(c.dim(`ended:     ${input.meeting.endedAt}`));
	}

	// Participants
	lines.push("");
	lines.push(c.bold("Participants"));
	for (const p of input.participants) {
		const adapter = p.adapter ?? "—";
		const dropped = p.status === "dropped" ? c.red(" [dropped]") : "";
		lines.push(`  ${p.id.padEnd(16)} ${p.role.padEnd(12)} ${c.dim(adapter)}${dropped}`);
	}
	const memberCount = input.participants.filter((p) => p.role === "member").length;
	lines.push(
		c.dim(
			`  Symmetric peer deliberation — ${memberCount} member${
				memberCount === 1 ? "" : "s"
			} + 1 facilitator`,
		),
	);

	// Jobs summary
	if (input.jobs.length > 0) {
		lines.push("");
		lines.push(c.bold("Jobs"));
		for (const job of input.jobs) {
			const reason =
				job.terminationReason ?? job.cancelReason ?? job.error?.code ?? "(no reason)";
			const statusColored =
				job.status === "completed"
					? c.green(job.status)
					: job.status === "failed"
						? c.red(job.status)
						: job.status === "cancelled"
							? c.yellow(job.status)
							: c.cyan(job.status);
			lines.push(`  ${job.id}  ${statusColored}  ${reason}  lastSeq=${job.lastSeq}`);
		}
	}

	// Body
	lines.push("");
	lines.push(HR);
	if (input.events !== null) {
		for (const ev of input.events) {
			lines.push(`${c.dim(`seq=${ev.seq} ${ev.type} @${ev.at}`)}`);
			const payloadLines = JSON.stringify(ev.payload, null, 2).split("\n");
			for (const ln of payloadLines) {
				lines.push(`  ${ln}`);
			}
			lines.push("");
		}
	} else {
		const groups = groupByRound(input.messages);
		for (const group of groups) {
			const roundLabel = group.round === 0 ? "Opening" : `Round ${group.round}`;
			lines.push("");
			lines.push(c.bold(`── ${roundLabel} ${HR.slice(roundLabel.length + 4)}`));
			for (const m of group.messages) {
				const head =
					m.kind === "pass"
						? c.grey(`[r${m.round} ${m.author} passed]`)
						: m.kind === "system"
							? c.yellow(`[r${m.round} ⚠ system]`)
							: c.cyan(`[r${m.round} ${m.author} speech]`);
				lines.push(head);
				if (m.kind === "speech") {
					for (const ln of m.text.split("\n")) {
						lines.push(`  ${ln}`);
					}
				} else if (m.kind === "system") {
					lines.push(`  ${c.dim(truncate(m.text, 500))}`);
				}
			}
		}
	}

	lines.push("");
	lines.push(c.dim(`Generated by ai-meeting ${input.version} · ${input.generatedAt}`));
	return `${lines.join("\n")}\n`;
};
